name: Download and Pack Appx

on:
  push:
    branches:
      - uwp

jobs:
  download_and_pack:
    runs-on: windows-latest

    steps:
      - name: Download export.appx from Google Drive
        run: |
          curl -L -o export.appx "https://drive.google.com/uc?export=download&id=1ODdhUmh4KixddOP1QWGOHeZHAgjDYkL0"

      - name: Run MakeAppx pack
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat" ^
          && "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\makeappx.exe" pack /d "%extractDir%" /p export.appx

      - name: Upload appx file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: export-appx
          path: export.appx
