name: Download and Pack Appx

on:
  push:
    branches:
      - uwp

jobs:
  download_and_pack:
    runs-on: windows-latest

    steps:
      - name: Set up Developer Command Prompt for VS 2019
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"

      - name: Download export.appx from Google Drive
        run: |
          curl -L -o export.appx "https://drive.google.com/uc?export=download&id=1ODdhUmh4KixddOP1QWGOHeZHAgjDYkL0"

      - name: Run MakeAppx pack
        run: |
          makeappx pack /d "%extractDir%" /p export.appx

      - name: Upload appx file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: export-appx
          path: export.appx
