name: Re-Sign Package

on:
  push:
    branches:
      - uwp

jobs:
  re-sign-package:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download the .appx file from Google Drive
      - name: Download appx file
        run: |
          Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=1zOnmrj2t6FKpia5pCE8M9OktpnrqNjJS" -OutFile app-package.appx

      # Step 3: Download the re-sign application
      - name: Download re-sign application
        run: |
          Invoke-WebRequest -Uri "https://github.com/Empyreal96/Appx_Re-Sign/releases/download/1.1.1.0/PackageRe-Sign.Release.zip" -OutFile re-sign-tool.zip

      # Step 4: Unzip the re-sign application
      - name: Unzip re-sign tool
        run: |
          Expand-Archive -Path re-sign-tool.zip -DestinationPath re-sign-tool

      # Step 5: Run pkgrsn.exe directly with the `&` operator and correct path handling
      - name: Re-Sign App Package
        run: |
          $toolPath = "${{ github.workspace }}\re-sign-tool\PackageRe-Sign (Release)\pkgrsn.exe"
          $appxPath = "${{ github.workspace }}\app-package.appx"
          & "$toolPath" -a "$appxPath" --skip
        shell: pwsh

      # Step 6: Upload the re-signed .appx as an artifact
      - name: Upload re-signed appx artifact
        uses: actions/upload-artifact@v3
        with:
          name: re-signed-appx
          path: app-package.appx
