name: Download and Run Batch File

on:
  workflow_dispatch:

jobs:
  run-batch-file:
    runs-on: windows-latest

    steps:
    - name: Install 7-Zip
      run: choco install 7zip --yes

    - name: Download Batch File
      run: |
        Invoke-WebRequest -Uri "https://github.com/Gamr13/AutoRA/raw/main/RAScript.bat" -OutFile "RAScript.bat"

    - name: Run Batch File
      run: .\RAScript.bat

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: batch-file-output
        path: ./*
