name: Re-Sign Package

on:
  workflow_dispatch:

jobs:
  re-sign-package:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download the .appx file
      - name: Download appx file
        run: |
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/open?id=1zOnmrj2t6FKpia5pCE8M9OktpnrqNjJS&authuser=0" -OutFile app-package.appx

      # Step 3: Download the re-sign application
      - name: Download re-sign application
        run: |
          Invoke-WebRequest -Uri "https://github.com/Empyreal96/Appx_Re-Sign/releases/download/1.1.1.0/PackageRe-Sign.Release.zip" -OutFile re-sign-tool.zip

      # Step 4: Unzip the re-sign application
      - name: Unzip re-sign tool
        run: |
          Expand-Archive -Path re-sign-tool.zip -DestinationPath re-sign-tool

      # Step 5: Run pkgrsn.exe to re-sign the package
      - name: Re-Sign App Package
        run: |
          .\re-sign-tool\PackageRe-Sign\pkgrsn.exe -a app-package.appx --skip
