name: Build and Publish DuckStation UWP

on:
  workflow_dispatch: # Allows manual dispatch of the workflow

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure the full repository is checked out

      - name: Generate Self-Signed Certificate
        id: cert
        run: |
          $cert = New-SelfSignedCertificate -CertStoreLocation "Cert:\CurrentUser\My" -Subject "CN=MyUWPCert" -KeyAlgorithm RSA -KeyLength 2048 -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -KeyExportPolicy Exportable -NotAfter (Get-Date).AddYears(1)
          $thumbprint = $cert.Thumbprint
          echo "THUMBPRINT=$thumbprint" >> $GITHUB_ENV
        shell: pwsh

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: latest

      - name: Download and Extract Dependencies
        run: |
          echo "Downloading dependencies..."
          curl -L -o deps-x64.7z https://github.com/stenzek/duckstation-ext-qt-minimal/releases/download/latest/deps-x64.7z
          echo "Extracting dependencies..."
          7z x deps-x64.7z -odep\msvc

      - name: Restore NuGet Packages
        run: nuget restore duckstation.sln

      - name: Build DuckStation UWP Project
        shell: pwsh
        run: |
          echo "Building DuckStation UWP project..."
          msbuild duckstation.sln /p:Configuration=ReleaseUWP /p:Platform=x64 /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=$env:THUMBPRINT /t:Restore,Build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DuckStation-UWP-Build
          path: ${{ github.workspace }}/duckstation-uwp/AppPackages
